# конструкция try-except служит защитой от неверно введенных данных
try:
    # Ввод исходных данных
    first = int(input("Введите первое целое число: "))  
    second = int(input("Введите второе целое число: "))
    third = int(input("Введите третье целое число: "))
    # обработка введенных чисел и вывод результата
    if first == second == third:
        print(3)
    elif first == second or second == third or first == third:
        print(2)
    else:
        print(0)
except ValueError as err:
    print("Ошибка! Введено нецелое число") #  описание ошибки для обычного пользователя
    print("Для программистов:", err) #  продвинутое описание ошибки
